-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 24, 2023 at 08:19 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `itadakimasu`
--

-- --------------------------------------------------------

--
-- Table structure for table `foods`
--

CREATE TABLE `foods` (
  `id` int(3) NOT NULL,
  `foods` varchar(40) NOT NULL,
  `description` varchar(400) NOT NULL,
  `image` varchar(400) DEFAULT NULL,
  `author` varchar(50) DEFAULT NULL,
  `instructions` varchar(2000) DEFAULT NULL,
  `ingredients` varchar(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `foods`
--

INSERT INTO `foods` (`id`, `foods`, `description`, `image`, `author`, `instructions`, `ingredients`) VALUES
(1, 'Garlic Fried Rice', 'Garlic Fried Rice or Sinangag is steamed rice fried with lots of garlic. This is a favorite side in the Philippines and most of Asia since rice is considered as the staple food.      ', 'https://imagizer.imageshack.com/img924/4168/8E3nvJ.jpg', 'Vanjo Merano', 'First, combine rice and salt then mix well. Next, heat the pan and pour the cooking oil. When the oil is hot enough, put-in the garlic and cook until color turns brown and texture is crispy. After that, add half of the rice and mix the rice well with the garlic while frying. Lastly, add the remaining half then cook for 5 minutes or until the rice is done. emove from the pan and place in a serving plate. Garnish with fried garlic on top.Serve hot with your favorite main dish. Share and Enjoy!\r\n', ''),
(2, 'Danggit Silog\n', 'This is a recipe for Danggit Silog. Dried Danggit or\nRabbitfish are fried until crispy and then served with\nsinangag (garlic fried rice), and fried egg.', 'https://imagizer.imageshack.com/img922/562/NuSWFK.jpg', 'Vanjo Merano', 'First, heat a medium sized frying pan and then pour the oil in. Once the oil starts to get hot, crack one egg open and then gently drop it on the pan to fry in medium heat. Tilt the pan on one side until most of the oil settles and then slowly push the oil towards the egg to coat the top part. Do this multiple times until the yellow part of the egg gets cooked. You will know when you are done if it turns out yellowish-white just like in the picture above. Do this step on the remaining eggs. Once done, set the fried eggs aside. Fry the danggit using the remaining oil. Make sure that the oil is hot before starting. Fry one side in medium heat until crispy and then turn the fish over to cook the other side.Transfer to a plate lined with paper towel. Note: frying danggit should be quick. Arrange a cup of garlic fried rice, a piece ofmakes an individual serving. Serve with spicy vinegar. Share and enjoy!', ''),
(3, 'Tosilog', 'Tocilog is a popular Filipino breakfast meal. The name tosilog was derived from the different components of the meal which are: Tocino (cured pork), Sinangag (Filipino garlic fried rice), and Sunny-side up egg. Tosilog is best eaten with a spicy vinegar dip. ', 'https://imagizer.imageshack.com/img924/989/qYTV08.jpg', 'Vanjo Merano', 'First, boil the water in a cooking pot. Next, once the water starts to boil, pour-in the cooking oil and add the uncooked tocino. Boil in medium heat until the water evaporates. Next, once the water completely evaporate, the oil will be left behind. Let one side of the tocino cook in oil for 3 minutes. Flip the tocino and cook the other side for the same time. Next, arrange the cooked tocino with the eggs in individual plates. Meanwhile, remove the excess oil in the cooking pot where the tocino was cooked. Heat the same pot and put-in the sinangag. Cook the fried rice for 1 minute while tossing. The residue from the tocino will stick to the fried rice making it more tasty. Next, arrange the fried rice with the tocino in individual plates. Next, Serve with spiced vinegar. Share and enjoy!', ''),
(4, 'Longsilog', 'Longsilog is a breakfast that consists of sweet pork (longanisa), savory eggs, and umami garlic rice!', 'https://imagizer.imageshack.com/img922/3457/vRlg9T.jpg', 'Vanjo Merano', 'First, heat 2 tablespoons of oil in a pan. Once the oil gets hot, fry the eggs. Remove from the pan. Set aside. Next, add remaining oil in the pan. Fry the longanisa until the outer part turns light brown (around 1 1/2 minutes). Next, pour-in water. Let boil. Continue boiling until the water evaporates. Fry the longanisa in remaining oil until fully cooked. Remove from the pan and set aside. Next, using the remaining oil, cook garlic until it starts to turn light brown. Next, add rice. Stir-fry for 3 minutes. Season with salt and ground black pepper. Next, assemble the fried eggs, longanisa, and sinangag on a plate. Serve with spicy vinegar as a dipping sauce for the longanisa. Share and enjoy!', ''),
(5, 'Corned Beef Silog', 'This is a recipe for Corned Beef Silog. It is a meal composed of sauteed corned beef, fried egg, and garlic fried rice.', 'https://imagizer.imageshack.com/img923/2941/AaBoUw.jpg', 'Vanjo Merano', 'First, heat oil on a pan. Once the oil gets hot, crack an egg and fry sunny-side-up. Remove the fried egg and place in a plate. Do this step until all 3 eggs are cooked. Next, using the remaining oil, sauté the garlic until it turns medium brown. Add the onion and sauté until it softens. Next, add the corned beef. Sauté for 2 minutes. Next, pour the beef broth in the pan. Continue to cook for 2 to 3 minutes or until the liquid evaporate. Add salt and pepper to taste. Next, arrange a cup of sinangag (garlic fried rice) and a piece of egg on a plate. Put 1/3 of the cooked corned beef. Do this step on all 3 plates. Serve. ', ''),
(6, 'Scrambled Egg', 'Filipino Scrambled Eggs is a classic breakfast dish made of eggs, tomatoes, and onions. It’s quick and easy to make yet so hearty and tasty. Perfect for breakfast, brunch, or any meal of the day! ', 'https://imagizer.imageshack.com/img923/511/AuXjr3.jpg', 'Lalaine Manalo', 'In a large bowl, break the eggs and whisk until fluffy and without streaks of white. Set aside. In a pan over low heat, add butter. When it begins to melt, add onions and cook until softened. Next, add tomatoes and cook, mashing with the back of the spoon, until softened and release juice. Season with salt and pepper to taste. Next, add beaten eggs over the tomato-onion mixture and allow to cook without stirring for about 20 to 30 seconds. Next, when it begins to set, gently fold with tomatoes and onions until combined. Next, continue to cook until eggs are just set but still slightly wet. Next, eason with salt and pepper to taste. Remove from the pan and serve immediately.', ''),
(7, 'Tortang Talong', 'Tortang Talong is an easy Filipino dish that is made with grilled whole eggplants, then peeled and pan-fried with an egg, flour, and spice mixture. The word talong means “eggplant” and torta means “omelette” or “flat cake” which being combined makes “eggplant omelette“.', 'https://imagizer.imageshack.com/img923/4553/T7nMTb.jpg', 'Vanjo Merano', 'First, grill the eggplant until the color of skin turns almost black. Next, let the eggplant cool for a while then peel off the skin. Set aside. Next, crack the eggs and place in a bowl. Add salt and beat. Next, place the eggplant on a flat surface and flatten using a fork. Dip the flattened eggplant in the beaten egg mixture. Next, heat the pan and pour the cooking oil. Next, fry the eggplant (that was dipped in the beaten mixture). Makes sure that both sides are cooked. Frying time will take you about 3 to 4 minutes per side on medium heat.', ''),
(8, 'Champorado', 'Champorado or tsampurado is a sweet chocolate rice porridge made with sticky rice and tablea.', 'https://www.foxyfolksy.com/wp-content/uploads/2017/06/champorado-recipe-1.jpg', 'Lhaz Alvarez', 'First, In a deep pot over medium heat, add water and bring to a boil. Next, add rice and stir to distribute. Lower heat and continue to cook, stirring occasionally, until rice begins to expand. Next, add tablea and cook, stirring regularly, until chocolate has melted. Continue to cook until rice is translucent and liquid is reduced to desired consistency. Next, Add sugar and continue to cook, stirring regularly, until dissolved. Lastly, ladle onto bowls, drizzle with evaporated milk and serve hot.', ''),
(9, 'Lugaw', 'Lugaw is a Filipino porridge primarily of rice, water, and salt. It is usually topped with hardboiled egg, crispy toasted garlic bits, and chopped spring onions.', 'https://imagizer.imageshack.com/img924/4342/kZnrWR.jpg', 'Lhas Alvarez', 'First, make hard-boiled eggs: Fill a pot with water and heat it up until it\'s just about to simmer. You should see a few bubbles start to form. Next, add in the eggs, then bring it up to a boil. Set the timer for 10 minutes. Meanwhile, prepare an ice bath: fill a bowl with water and ice. As soon as the timer goes off, transfer the eggs to the ice bath to stop the cooking process. Once the eggs are cool enough to handle, they can be peeled. Set aside. Lastly, make toasted garlic bits: In a cold pan, add 8 tablespoons oil and minced garlic. Then, turn on the heat to low-medium. Saute the garlic, making sure to keep tossing, until it is golden brown. Do not leave unattended.', ''),
(10, 'Arroz Caldo', 'Arroz caldo is a comforting and flavorsome Filipino rice and chicken soup served mainly as a snack but can be enjoyed any time of the day.', 'https://imagizer.imageshack.com/img924/6228/nTlqhz.jpg', 'Lola', 'First, heat oil in a large pot over medium heat.  Cook and stir onion, garlic, and ginger in hot oil until fragrant,  about 5 minutes. Add chicken wings; cook and stir for 1 minute.  Stir in fish sauce, cover, and cook another 2 minutes.  Next, pour chicken broth into the pot. Stir in sweet rice  and bring mixture to a boil. Cover and cook for 10 minutes,  stirring occasionally to prevent rice from sticking to the bottom  of the pot. Season with salt and pepper. Lastly, portion soup into  bowls First, Heat oil in a large pot over medium heat. Cook and stir onion, garlic, and ginger in hot oil until fragrant, about 5 minutes. Add chicken wings; cook and stir for 1 minute. Stir in fish sauce, cover, and cook another 2 minutes. Next, pour chicken broth into the pot. Stir in sweet rice and bring mixture to a boil. Cover and cook for 10 minutes, stirring occasionally to prevent rice from sticking to the bottom of the pot. Season with salt and pepper. Lastly, portion soup into bowls and garnish with green onion. Serve with lemon slices and additional fish sauce, if desired.\n', ''),
(11, 'Tuyo with Rice & Kamatis', 'Tuyo fish is a type of Filipino sun dried fish. This is usually fried quickly and eaten with spicy vinegar dip and rice. Tuyo is usually consumed for breakfast in the Philippines, although this dried fish can also be eaten for anytime of the day.', 'https://imagizer.imageshack.com/img922/2151/4Wd75Z.jpg', 'Vanjo Merano', 'First, preheat oven to 400F. Next, Arrange the tuyo  fish in an aluminum foil sheet. Spray both sides of the  fish with cooking oil. Secure the fish inside the sheet  by covering with another aluminum sheet and secure the sides.  Next, Open your vent (this is important). Bake for 6 to  10 minutes.Next,Remove the fish from the sealed sheet and  arrange in individual plates with a cup of white rice and  wedged tomato.Next, Serve with spiced vinegar.  And lastly, Share and enjoy!First, preheat oven to 400F. Next, arrange the tuyo fish in an aluminum foil sheet. Spray both sides of the fish with cooking oil. Secure the fish inside the sheet by covering with another aluminum sheet and secure the sides. Next, open your vent (this is important). Bake for 6 to 10 minutes. Next, remove the fish from the sealed sheet and arrange in individual plates with a cup of white rice and wedged tomato. Serve with spiced vinegar.', ''),
(12, 'Maruya', 'Banana Fritter is a type of Filipino snack. It is a fried concoction made from ripe  “Saba” banana or plantains. The bananas can either be sliced or mashed. It is then mixed with a batter composed of flour, sugar, vanilla, and egg.', 'https://imagizer.imageshack.com/img922/774/qReoAG.jpg', 'Lalaine Manalo', 'In a bowl, sift together flour, 1/4 cup of the sugar, baking powder, and salt. Next, In a large bowl, beat egg. Next, Add milk and butter and whisk together until blended. Next, Add flour mixture to milk mixture and stir until just moistened. DO NOT OVERMIX. Next, In a pan over medium heat, heat oil. Next, Dip banana slices into batter to fully coat and gently slide into hot oil. Next, Cook for about 1 to 2 minutes on each side or until golden and crisp. Remove from pan and drain on paper towels. Lastly, Using a fine-mesh sieve, dust maruya with the remaining sugar. Serve warm.', ''),
(13, 'Tortang Giniling', 'Tortang Giniling or Ground Meat Omelet is a type of Filipino omelet wherein ground meat (beef and pork being the most common) is sautéed with vegetables such as garlic, onions, and tomatoes then mixed directly with beaten eggs.', 'https://imagizer.imageshack.com/img923/3186/VFMjPD.jpg', '   Lola', 'First, heat a frying pan or wok and pour-in 2 tablespoons of cooking oil. Next, when the oil is hot enough, sauté the onion, garlic, and tomato. Next, add the ground meat and cook for 8 to 10 minutes. Next, put-in the bell peppers and green peas. Cook for 3 minutes. Next, add salt and pepper then stir to distribute. Transfer to a large bowl. Let it cool down. Next, when the cooked ground meat reaches room temperature, beat the eggs and pour into the bowl same bowl. Stir to distribute all the ingredients. Next, heat a clean non-stick pan. Add the remaining cooking oil. Next, scoop 1/3 of the egg and pork mixture to the pan. Next, cook each side for 3 minutes or until you see that the eggs are fully cooked. Avoid overcooking the eggs. Do the same step until the mixture is consumed. Next, turn off the heat and transfer to a serving plate. Lastly, serve with banana ketchup. Share and enjoy!', ''),
(14, 'Tortang Tuna', 'Tortang Tuna with Spinach is a type of omelet wherein sautéed tuna and spinach are added to the beaten egg mixture before cooking. This is a practical way to make stuffed omelet. ', 'https://imagizer.imageshack.com/img922/896/vtsgXT.jpg', 'Knorr', 'First, heat 3 tablespoons of cooking oil in a pan.  Next, saute onion until soft Next, add tuna.  Continue to cook for 2 minutes. Next, season with  salt and ground black pepper. Remove from the pan  and let it cool down. Next, crack the eggs and place  in a large mixing bowl. Beat until yellow and white  parts are well blended. Next, add the sautéed tuna  to beaten eggs. Make sure that the temperature cools  first. Mix well. Next, Heat remaining oil in an omelet  pan or small frying pan. Next, First, Heat 3 tablespoons of cooking oil in a pan. Next, saute onion until soft Next, add tuna. Continue to cook for 2 minutes. Next, season with salt and ground black pepper. Remove from the pan and let it cool down. Next, crack the eggs and place in a large mixing bowl. Beat until yellow and white parts are well blended. Next, add the sautéed tuna to beaten eggs. Make sure that the temperature cools first. Mix well. Next, Heat remaining oil in an omelet pan or small frying pan. Next, pour the egg and tuna mixture. Gently push the cooked portion of the omelet towards the center to be able to heat the uncooked mixture. Continue to cook between low to medium heat for 2 minutes or until completely cooked. Turn over the omelet to cook the opposite side. Next, transfer to a serving plate. Serve. ', ''),
(15, 'Ginisang Sardinas', 'Ginisang Sardinas or Sauteed Sardines is a quick\ncanned sardines in tomato sauce recipe that is eaten\nbest with rice or pandesal.', 'https://imagizer.imageshack.com/img922/1677/pajUoT.jpg', 'Vanjo Merano', 'First, heat the oil in a pan. Next, sauté the garlic and onion. Next, when the onion becomes soft, add the tomato and cook for 3 minutes. Next, pour-in the sardines in tomato sauce and chili. Stir and let boil. Next, cook for 5 minutes in low to medium heat. You may add a little water if needed. Next, add-in the lemon juice, ground black pepper, and salt or fish sauce. Stir and cook for a minute more. Next, turn off heat and then transfer to a serving bowl. Garnish with chopped flat leaf parsley. Next, serve with steamed rice. Share and enjoy!', ''),
(16, 'Tinapa Fried Rice', 'Tinapa Fried Rice is a fried rice version that makes use of smoked fish flakes.', 'https://imagizer.imageshack.com/img922/2628/y52gCz.jpg', 'Knorr', 'First, get a medium-sized pan, big enough to fit the rice later, make it nice and warm over medium heat. Add the oil and start by frying the Tinapa fish. Once cooked, set aside to let it cool, then shred to turn it into fish flakes. Next, using the same pan, add the beaten eggs and the crushed 1/2 Knorr chicken cubes. Stir the gg mix until all is cooked. Next, add the carrots and green peas, then add the rice and the remaining 1/2 Knorr Chicken cube. Mix until dissolved and all ingredients are well incorporated. Continue to cook and mix until vegetables are fully cooked. Lastly, serve hot and enjoy!', ''),
(17, 'Ramen', 'Ramen is a Japanese noodle soup, with a combination of a rich flavoured broth, one of a variety of types of noodle and a selection of meats or vegetables, often topped with a boiled egg. ', 'https://imagizer.imageshack.com/img924/3497/Agz8lD.jpg', ' Damn Delicious', 'First, place eggs in a large saucepan and cover with cold water by 1 inch. Bring to a boil and cook for 1 minute. Next, cover eggs with a tight-fitting lid and remove from heat; set aside for 8-10 minutes. Drain well and let cool before peeling and halving. After that, heat olive oil in a large stockpot or Dutch oven over medium heat. Add garlic and ginger, and cook, stirring frequently, until fragrant, about 1-2 minutes. Then, whisk in chicken broth, mushrooms, soy sauce and 3 cups water. Next is bring to a boil; reduce heat and simmer until mushrooms have softened, about 10 minutes. Stir in Yaki-Soba until loosened and cooked through, about 2-3 minutes. Lastly, stir in spinach, Narutomaki, carrot and green onions until the spinach begins to wilt, about 2 minutes. Serve immediately, garnished with eggs.', ''),
(18, 'Japanese Beef Curry', 'Japanese curry is a thick curry with a stew-like consistency and commonly includes a protein, sweet onions, carrots, and potatoes.', 'https://imagizer.imageshack.com/img922/157/s8wGlW.jpg', 'Raymund', 'First, in a pot add oil then brown beef on all sides, once done set aside. Add the onions, garlic and ginger then sauté until onions are soft. After that, add the grated apple, beef and enough water just to cover the beef, bring to a boil then simmer for 1 hour. Add the carrots and potatoes then simmer for 20 minutes. You can also add water if necessary. Lastly, add the tomato paste and curry roux, simmer for additional 10 minutes. Season with salt then serve with freshly steamed rice. Cut two sFirst, in a pot add oil then brown beef on all sides, once done set aside. Add the onions, garlic and ginger then sauté until onions are soft. After that, add the grated apple, beef and enough water just to cover the beef, bring to a boil then simmer for 1 hour. Add the carrots and potatoes then simmer for 20 minutes. You can also add water if necessary. Lastly, add the tomato paste and curry roux, simmer for additional 10 minutes. Season with salt then serve with freshly steamed rice.', ''),
(19, 'Pork Tonkatsu', 'Tonkatsu, or pork cutlet, is a Japanese dish of pork filet that is breaded with panko breadcrumbs and deep-fried. It is traditionally served with a dark, savory tonkatsu sauce and shredded green cabbage.', 'https://imagizer.imageshack.com/img922/8391/BwPZ4t.jpg', 'Lalaine Manalo', 'Cut two slits about 2 inches apart through the fat and connective tissue on each of the pork chops. Season with salt and pepper to taste. In wide heavy bottomed skillet over medium heat, heat about 2-inches deep of oil to about 350 F. Next is to place flour in one plate, the bread crumbs in another plate, and the beaten eggs in a bowl. Lightly dredge pork chop in flour, dip in eggs and then roll in bread crumbs, patting down crumbs to fully coat. Repeat with remaining pork chops. After that, add pork chops into hot oil and deep-fry, turning as needed, for about 8 to 10 minutes or until breading is golden and pork is cooked through. Lastly, remove from pan and drain on a wire rack set over a baking sheet. Let rest for about 2 to 3 minutes before slicing. Serve with a generous heap of shredded cabbage and a side of tonkatsu sauce.', ''),
(20, 'Tamagoyaki', 'In Japanese, tamago means egg and yaki means grill, so tamagoyaki literally translates to ‘grilled egg’. This classic dish is made by rolling together thin omelettes in a frying pan, folding them into a layered log, and then sliced into pillows.', 'https://imagizer.imageshack.com/img923/2199/ELHLBR.jpg', 'Pokerman11', 'First, beat eggs thoroughly in a bowl; whisk in dashi stock, sugar, mirin, and soy sauce until sugar has dissolved. Lightly grease a nonstick skillet and heat over medium heat. Then pour a thin layer of egg mixture into the hot pan and swirl to coat the pan. Cook until egg layer is firm on the bottom but still slightly liquid on top, about 1 minute. Then lift up one edge using a spatula and roll up the egg layer. Push omelet roll to one side of the skillet. Oil the skillet again and pour in another thin layer of egg, lifting the first omelet roll up slightly to allow the egg to flow underneath; roll up the first omelet in the new layer of egg and push omelet to the edge of the skillet as before. Repeat the process with the remaining egg mixture, oiling the pan each time if needed. Lastly, remove rolled omelet to a serving platter and cut into 6 equal pieces to serve. Add water if necessary.', ''),
(21, 'Yaki Onigiri', 'Rice is the main food source in Japan and no meal would be complete without a bowl of steamed rice on the table. Japanese rice is white, short grain, and has a fluffy and slightly sticky texture. It is known by several names, including sushi rice, Calrose rice, short-grain rice, or Japonica.\r\n\r\n', 'https://imagizer.imageshack.com/img924/6527/BELJVI.jpg', 'Jamie\n', 'First, wet your hands with water and take about ⅓ to ½ cup of warm rice in your hands. Using both hands, firmly press the rice into a triangular shape. Next is to fill the mold with the appropriate amount of rice and firmly press to create your shape. After that, heat a pan over medium heat and add the oil. Grill each side of the rice ball until a crispy, golden-brown crust forms. Avoid flipping often to keep the shape intact. Then lower to low heat and brush one side with soy sauce and flip to carameliz the sauce slightly. Check after 15 to 30 seconds as it can easily burn. Last is to brush the other side with soy sauce and flip to caramelize that side. Serve and optionally sprinkle with furikake while still hot. Enjoy!', ''),
(22, 'Mochi', 'Mochi is a bun-shaped Japanese dessert made from sweet glutinous rice flour, or mochigome. It has a soft, chewy texture that is somewhat elastic.\r\n\r\n', 'https://imagizer.imageshack.com/img924/5338/dp2s9n.jpg', 'Honest Food Talks', 'First, mix the glutinous rice flour with sugar in a medium, microwavable baking bowl. Then add the water until it is well combined. After that, loosely cover the bowl with plastic wrap and cook it for one minute on high heat. Remove the mixture from the microwave, use a wet rubber spatula to stir it. Recover and cook the mixture for another minute. Next, remove the mixture and stir again, checking for colour and consistency.It should be almost transparent and resemble dough. If not, microwave in 30-second increments, stirring in between. Spread the starch across the working surface and drop the dough on it, then dust it with more starch to make handling easier. Roll it out with a rolling pin and refrigerate for 12 minutes. Then remove the dough and cut it into nine-centimetre circles. Lastly, fill each circle and pinch the opposite sides together until each daifuku mochi is completely sealed.', ''),
(23, 'Omurice', 'Omurice, or Japanese omelette rice, is an incredibly popular home-cooked dish originating in Japan and enjoyed all across the globe as one of the most iconic Japanese dishes.\n\n', 'https://imagizer.imageshack.com/img924/6602/PLgO71.jpg', 'Cookeru', 'First, mix the glutinous rice flour with sugar in a medium, microwavable baking bowl. Then add the water until it is well combined. After that, loosely cover the bowl with plastic wrap and cook it for one minute on high heat. Remove the mixture from the microwave, use a wet rubber spatula to stir it. Recover and cook the mixture for another minute. Next, remove the mixture and stir again, checking for colour and consistency.It should be almost transparent and resemble dough. If not, microwave in 30-second increments, stirring in between. Spread the starch across the working surface and drop the dough on it, then dust it with more starch to make handling easier. Roll it out with a rolling pin and refrigerate for 12 minutes. Then remove the dough and cut it into nine-centimetre circles. Lastly, fill each circle and pinch the opposite sides together until each daifuku mochi is completely sealed.', ''),
(24, 'Chicken Teriyaki', 'This Chicken Teriyaki recipe makes use of boneless chicken breasts. It is marinated in special homemade Teriyaki sauce and then grilled while being basted with a sweet basting sauce.\r\n\r\n\r\n', 'https://imagizer.imageshack.com/img924/1908/WMrc6x.jpg', 'Vanjo ', 'Combine all the marinade ingredients. Mix well. Then combine the basting sauce ingredients. Set aside. Place the chicken breasts in a re-sealable Ziploc bag and then pour-in the marinade. After that, seal the bag and then place it in the fridge to marinate for 2 hours. Grill both sides of the chicken for 7 to 10 minutes while basting using the basting sauce. You may flip the chicken once in a while keep them from being burnt. Lastly, transfer to a serving plate and then garnish with sesame seeds. Serve. Share and enjoy!\n', ''),
(25, 'Miso Soup', 'Miso soup is a traditional Japanese soup consisting of a dashi stock into which softened miso paste is mixed.\r\n\r\n', 'https://imagizer.imageshack.com/img922/5909/NrHlux.jpg', 'Love & Lemons', 'First, gently rinse the kombu piece. Place it in a medium pot with the water and gently simmer for 10 minutes. Don’t let it boil, or the kombu flavor will turn bitter. Next, soak the wakame in a small bowl of warm water for at least 5 minutes to rehydrate. Remove the kombu from the soup. After that, in a small bowl, stir the miso paste together with some of the hot broth until the mixture is smooth, then stir it back into the soup. Lastly, drain the wakame and add it to the soup pot along with the scallions and tofu. Simmer over very low heat for 1 to 2 minutes. Season, to taste, with tamari.', ''),
(26, 'Oyakodon', 'Oyakodon is a delicious traditional Japanese meal consisting 0f chicken sautéed and then cooked in a Japanese broth, andthen finished with egg and served over rice.\r\n', 'https://imagizer.imageshack.com/img923/718/hvT3g9.jpg', 'All Recipes', 'Heat oil in a large skillet over medium heat. Add chicken and cook until beginning to brown, about 5 minutes. Add onion; cook and stir until onion is translucent, about 5 minutes. Pour in stock, then whisk in soy sauce, mirin, and brown sugar; stir until sugar dissolves. Bring to a boil, then lower heat and simmer until slightly reduced, about 10 minutes. Whisk eggs in a bowl until well-beaten, then pour into the hot stock mixture. Cover the skillet, reduce the heat, and steam until egg is cooked, about 5 minutes. Remove from the heat. Divide rice among 4 deep soup bowls and top with equal amounts of the soup mixture.', ''),
(27, 'Yakimeshi', 'Yakimeshi literally means fried rice. It’s a rice dish that’s made using leftovers such as eggs, veggies, meats and seafood.', 'https://imagizer.imageshack.com/img922/3889/uEIlY3.jpg\n', 'Shihoko | Chopstick Chronicles', 'In a small bowl, mix the mayonnaise well with the cooked rice. Chop the green shallots and bacon into small pieces. Heat a little olive oil in a frying pan over high heat then add the rice and fry for a few minutes. Put the rice to one side of the pan and add the eggs and scramble them. Once the egg is half cooked, stir it into the rice. Add the bacon and cook for about 5 minutes. Add the shallots and salt and stir for a bit. Remove from the heat and sprinkle a bit of pepper and serve!', ''),
(28, 'Japanese Egg Sandwich', 'Japanese Egg Sandwiches or Tamago Sando are the Japanese take on egg salad sandwiches. With a flavorful egg salad made with Japanese mayonnaise, sandwiched between milk bread, it has a comforting taste and texture that makes it one of the most popular sandwiches in Japan.', 'https://imagizer.imageshack.com/img923/8355/ERiBIv.jpg', 'No Recipes', 'Roughly chop the remaining two eggs and add them to a bowl. along with the mayonnaise, mustard, white pepper, onion powder, and salt. Mix well to combine. Place two slices of sandwich bread on a flat surface and add the halved eggs to one slice with the tapered end of each egg pointing towards opposite corners. Cover the halved egg with the egg salad mixture. Place the second slice of bread over the first, and gently press the edges down to mold the bread to the shape of the eggs. Cut the crust off if you like and then slice the sandwich diagonally to reveal the halved eggs in the center.', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `foods`
--
ALTER TABLE `foods`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `foods`
--
ALTER TABLE `foods`
  MODIFY `id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
